plugin_spec_version: v2
extension: plugin
products: [insightconnent, insightidr]
name: cortex_xdr
title: Cortex XDR
description: cortex xdr
version: 1.0.0
vendor: rapid7
support: rapid7
status: []
tags: [cortex, xdr]

types:
  endpoint:
    agent_id:
      title: "Agent ID"
      type: string
      description: "Agent iD"
      required: false
    agent_status:
      title: "Agent Status"
      type: string
      description: "Agent status"
      required: false
    host_name:
      title: "Hostname"
      type: string
      description: "Hostname"
      required: false
    agent_type:
      title: "Agent Type"
      type: string
      description: "Agent type"
      required: false
    ip:
      title: "Ip"
      type: "[]string"
      description: "Ip"
      required: false
    last_seen:
      title: "Last Seen"
      type: integer
      description: "Last seen"
      required: false


connection:
  fqdn:
    title: FQDN
    description: Fully qualified domain name
    type: string
    required: true
    example: https://api-example.xdr.us.paloaltonetworks.com/
  api_key_id:
    title: API Key ID
    description: The API Key ID shown in the API Keys table in settings. e.g. 1, 2, 3
    type: int
    required: true
    example: 1
  api_key:
    title: API Key
    description: The API Key that is generated when creating a new key
    type: credential_secret_key
    required: true
    example: '1234123412341234asdfasdfasdfasdfasdf1234123412341234123412341234asdfasdfasdfasdfasdf123412341234123412341234asdfasdfasdfasdfasdf'
  security_level:
    title: Security Level
    description: The Security Level of the key provided. This can be found in the API Key settings table in the Cortex XDR settings
    type: string
    required: true
    example: Standard
    default: Standard
    enum:
      - Advanced
      - Standard
actions:
  get_endpoint_details_by_hostname:
    title: Get Endpoint Details
    description: Get information about an endpoint
    input:
      hostname:
        title: Hostname
        description: The hostname to get information about
        type: string
        required: true
        example: example-host
    output:
      endpoints:
        title: Endpoints
        description: Any endpoints that match the given hostname
        type: "[]endpoint"
        required: true

triggers:
  get_incidents:
    title: Get Incidents
    description: Get Incidents
    input:
      time_field:
        title: Time Field
        description: Which time field to filter and sort on
        type: string
        required: true
        enum:
          - "modification_time"
          - "creation_time"
        example: "creation_time"
    output:
      incident:
        title: Incident
        description: Incident
        type: object
        required: false




