apiVersion: v1
kind: Pod
metadata:
  name: vulndb
  labels:
    type: plugin
    vendor: rapid7
    app: vulndb
spec:
  containers:
    - name: rapid7-vulndb
      image: rapid7/rapid7_vulndb:2.0.0
      imagePullPolicy: IfNotPresent
      args:
        - http
